rootless-containers/usernetes

- .gitignore
- .travis.yml
- README.md
- Taskfile.yml
- build/Taskfile.yml
- build/kubernetes.Dockerfile
- build/moby.Dockerfile
- dockercli.sh
- kubectl.sh
- run.sh
> add the build script

- README.md
- Taskfile.yml
- build/Taskfile.yml
- kubectl.sh
- run.sh
> moby: allow using overlay2 (Ubuntu-only)

- LICENSE-slirp4netns
- LICENSE-task
- README.md
> add LICENSE-slirp4netns and LICENSE-task

- build/Taskfile.yml
- build/kubernetes.Dockerfile
- build/moby.Dockerfile
- build/patches/README.md
- build/patches/kubernetes/0001-kubelet-cm-ignore-sysctl-error-when-running-in-usern.patch
- build/patches/kubernetes/0002-dockershim-ignore-GetCheckpoint-error-when-running-i.patch
- build/patches/kubernetes/0003-POC-kubelet-cm-ignore-cgroups-error-when-running-in-.patch
- build/patches/moby/0001-allow-running-dockerd-in-an-unprivileged-user-namesp.patch
Experimentally moving the patch set into this repo.
This would be helpful for promoting collaborative work and for tracking our changes.
Please refer to `build/patches/README.md` for further information.
- - -
Close #16 
cc @cyphar @giuseppe
> Import patch set from AkihiroSuda/{moby,kubernetes}

- Taskfile.yml
- run.sh
> crio: set up /etc/containers/policy.json

- Taskfile.yml
- run.sh
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
> Taskfile.yml: crio uses policy.json from home directory

- build/Taskfile.yml
- build/crio.Dockerfile
Closes: https://github.com/rootless-containers/usernetes/issues/39
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
> crio: use a working commit for the CNI plugins

- build/Taskfile.yml
- build/kubernetes.Dockerfile
- build/patches/kubernetes/0001-kubelet-cm-ignore-sysctl-error-when-running-in-usern.patch
- build/patches/kubernetes/0002-dockershim-ignore-GetCheckpoint-error-when-running-i.patch
- build/patches/kubernetes/0003-POC-kubelet-cm-ignore-cgroups-error-when-running-in-.patch
- build/patches/kubernetes/0004-kube-proxy-allow-running-in-userns.patch
- build/patches/moby/0001-pkg-archive-support-overlayfs-in-userns-Ubuntu-kerne.patch
- build/patches/moby/0002-allow-running-dockerd-in-an-unprivileged-user-namesp.patch
- build/rootlesskit.Dockerfile
> update Moby and Kubernetes

- .travis.yml
- build/Taskfile.yml
- build/crio.Dockerfile
> bump up crio

- build/Taskfile.yml
- build/kubernetes.Dockerfile
- build/moby.Dockerfile
- build/rootlesskit.Dockerfile
- build/slirp4netns.Dockerfile
> optimize build

- build/crio.Dockerfile
> build: use multi-stage crio.Dockerfile 

- build/crio.Dockerfile
Fix https://github.com/rootless-containers/usernetes/issues/50
> build: fix crio.Dockerfile

- boot/crio.sh
> boot/crio.sh: fix mkdir

- Dockerfile
- README.md
- docs/binary-release-license/LICENSE-socat
> build socat binary

- Dockerfile
- boot/rootlesskit.sh
> launch slirp4netns/rootlesskit with --disable-host-loopback

- README.md
- Taskfile.yml
- docker-compose.yml
> docker-compose: docker+crio+containerd mixed cluster

- Dockerfile
- README.md
> Dockerfile: support Fedora images

- boot/rootlesskit.sh
> boot/rootlesskit.sh: allow overriding U7S_PARENT_IP

- Dockerfile
> fedora: add ps

- Makefile
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
> Makefile: print SHA256SUM

- boot/rootlesskit.sh
- common/common.inc.sh
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
> rootlesskit: isolate --pidns

- Dockerfile
- boot/rootlesskit.sh
- src/patches/kubernetes/0001-kubelet-cm-ignore-sysctl-error-when-running-in-usern.patch
- src/patches/kubernetes/0002-kube-proxy-allow-running-in-userns.patch
- src/patches/kubernetes/0003-kubelet-new-feature-gate-SupportNoneCgroupDriver.patch
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
> update components; enable slirp4netns-sandbox

- Dockerfile
- boot/rootlesskit.sh
- src/patches/kubernetes/0001-kubelet-cm-ignore-sysctl-error-when-running-in-usern.patch
- src/patches/kubernetes/0002-kube-proxy-allow-running-in-userns.patch
- src/patches/kubernetes/0003-kubelet-new-feature-gate-SupportNoneCgroupDriver.patch
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
> update components; enable slirp4netns-seccomp

- README.md
https://github.com/podenv/silverkube
Thanks @TristanCacqueray :tada:
> README.md: new adopter: Silverkube

- boot/rootlesskit.sh
- docker-compose.yml
> Follow up to #126

- Dockerfile
> Dockerfile: build Kubernetes without bazel

- .github/workflows/main.yaml
- Dockerfile
- README.md
- boot/containerd-fuse-overlayfs-grpc.sh
- boot/containerd.sh
- boot/crio.sh
- boot/docker-2ndboot.sh
- common/common.inc.sh
- docs/binary-release-license/LICENSE-crun
- docs/binary-release-license/LICENSE-fuse-overlayfs
- hack/show-latest-commits.sh
- install.sh
> Use fuse-overlayfs (on all distros)

- Dockerfile
- hack/smoketest.sh
> Remove unused CNI plugins

- README.md
- boot/kube-apiserver.sh
- boot/kubelet.sh
- common/cfssl.sh
- install.sh
- manifests/coredns.yaml
> Add CoreDNS

- .github/workflows/main.yaml
- manifests/coredns.yaml
Fix https://github.com/rootless-containers/usernetes/issues/184
> deflake coredns tests

- README.md
- Vagrantfile
- boot/rootlesskit.sh
- install.sh
> Allow kernel.dmesg_restrict=1

- .github/workflows/ghcr.yaml
- .github/workflows/main.yaml
- Makefile
- README.md
- docker-compose.yml
- hack/smoketest-docker.sh
> Migrate from Docker Hub to GHCR

- Makefile
> Silence `WARN[0000] The "U7S_NODE_NAME" variable is not set.`

- hack/create-cluster-lima.sh
> hack/create-cluster-lima.sh: support macOS hosts

- .github/workflows/main.yaml
- .github/workflows/reusable-multi-node.yaml
- .github/workflows/reusable-single-node.yaml
- Dockerfile
- Dockerfile.d/SHA256SUMS.d/flannel-v0.26.1
- Dockerfile.d/SHA256SUMS.d/helm-v3.16.3
- Makefile.d/install-flannel.sh
> CI: shrink test matrix, etc.

- Dockerfile.d/u7s-entrypoint.sh
- Makefile
- Makefile.d/install-flannel.sh
- docker-compose.yaml
- kubeadm-config.yaml
> Consistently remove "U7S_" prefix from all the variables
