rootless-containers/usernetes

README.md
Taskfile.yml

`--kubelet-https=false` was actually unneeded and did not work

kubernetes: make `kubectl run -it` functional

---

README.md
build/Taskfile.yml

`kubelet.go:1526:syncPod()` is updated to prevent pods from being killed
immediately due to `!pcm.Exists()`.
https://github.com/AkihiroSuda/kubernetes/commit/831875979e75426c7385cd1fff2355ce51b5a0f7#diff-bf28da68f62a8df6e99e447c4351122dR1526
Before we propose our change to the Kubernetes upstream, probably we need to
implement rootless PCM in the proper way.
Fix #10

[k8s] Prevent pods from being killed immediately

---

README.md
Taskfile.yml
build/Taskfile.yml
build/crio.Dockerfile

Depends on: https://github.com/kubernetes-incubator/cri-o/pull/1729
I will drop the WIP tag once it lands into CRIO upstream and can fix the commit used here.
Closes: https://github.com/rootless-containers/usernetes/issues/11
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

usernetes: add support for CRI-O

---

Taskfile.yml
build/crio.Dockerfile

Workaround for https://github.com/rootless-containers/usernetes/issues/19 (Ideally we should build it as a static binary)
cc @giuseppe

 crio: musl -> glibc

---

Taskfile.yml
build/Taskfile.yml
build/cni.Dockerfile
build/containerd.Dockerfile
build/crio.Dockerfile
build/moby.Dockerfile
build/rootlesskit.Dockerfile
build/runc.Dockerfile
build/slirp4netns.Dockerfile
config/crio/cni/10-cri-bridge.conf
config/crio/cni/99-loopback.conf

Preparation for adding containerd CRI
---
Before:
```
bin
├── crio
│   ├── cni
│   │   ├── conf
│   │   │   ├── 10-crio-bridge.conf
│   │   │   ├── 99-loopback.conf
│   │   │   └── README.md
│   │   └── plugins
│   │       ├── bandwidth
│   │       ├── bridge
│   │       ├── dhcp
│   │       ├── flannel
│   │       ├── host-device
│   │       ├── host-local
│   │       ├── ipvlan
│   │       ├── loopback
│   │       ├── macvlan
│   │       ├── portmap
│   │       ├── ptp
│   │       ├── sample
│   │       ├── static
│   │       ├── tuning
│   │       └── vlan
│   ├── conmon
│   ├── crio
│   └── runc
├── docker
├── etcd
├── etcdctl
├── hyperkube
├── moby
│   ├── containerd
│   ├── containerd-shim
│   ├── ctr
│   ├── docker-init
│   …
```

decouple runc and cni from crio ; decouple containerd from moby

---

boot/containerd.sh
boot/dockerd.sh
common/common.inc.sh

boot/dockerd.sh: use vfs storage driver on non-Ubuntu

---

Dockerfile

Dockerfile: fix non-BuildKit compatibility

---

Dockerfile
README.md
src/patches/kubernetes/0001-kubelet-cm-ignore-sysctl-error-when-running-in-usern.patch
src/patches/kubernetes/0002-dockershim-ignore-GetCheckpoint-error-when-running-i.patch
src/patches/kubernetes/0003-POC-kubelet-cm-ignore-cgroups-error-when-running-in-.patch
src/patches/kubernetes/0004-kube-proxy-allow-running-in-userns.patch

* CVE-2019-5736: https://github.com/opencontainers/runc/commit/0a8e4117e7f715d5fbeef398405813ce8e88558b
* CVE-2019-6778: https://github.com/rootless-containers/slirp4netns/commit/d7811709dbd63f3bb93de37ec803d22ff213ae14

update components (CVE-2019-5736, CVE-2019-6778)

---

README.md

On Debian GNU grep 3.3 without quote this grep current directory
cheers

README: quote grep

---

Dockerfile
boot/containerd.sh
boot/crio.sh
hack/show-latest-commits.sh
install.sh

Switching to crun, as crun is the defacto reference implementation of OCI for cgroup v2.

use crun instead of runc

---

.github/workflows/main.yaml
Dockerfile
README.md
Vagrantfile
boot/containerd.sh
boot/crio.sh
boot/kubelet.sh
boot/rootlesskit.sh
common/common.inc.sh
hack/smoketest-binaries.sh
hack/smoketest-common.inc.sh
hack/smoketest-manifests/test-limits.yaml
install.sh
src/patches/containerd/0001-DIRTY-VENDOR-cri-allow-disabling-hugepages.patch
src/patches/kubernetes/0001-kubelet-cm-ignore-sysctl-error-when-running-in-usern.patch
src/patches/kubernetes/0002-kube-proxy-allow-running-in-userns.patch
src/patches/kubernetes/0003-kubelet-new-feature-gate-SupportNoneCgroupDriver.patch
src/patches/kubernetes/0004-kubelet-new-feature-gate-Rootless.patch
uninstall.sh

Now resource limitation works. A container is executed in a cgroup like `/user.slice/user-1001.slice/user@1001.service/user.slice/cri-containerd-6938564e754ad86269a536ed19172af0eff5f7ff0a41eefc5b433a76f1f38f16.scope`. `cgroupsPerQOS` is currently unsupported.
Usage: `install.sh --cri=containerd --cgroup-manager=systemd`

support `--cgroup-manager=systemd` (requires cgroup v2 and containerd)

---

.github/workflows/main.yaml
Dockerfile
README.md
boot/crio.sh
boot/rootlesskit.sh
install.sh
src/patches/crio/0001-rootless-enable-resource-limit-when-cgroup-v2-contro.patch

Now `install.sh --cri=crio` supports resource limitation with cgroup2.
Host needs to be configured to enable cgroup v2 delegation.

crio: support resource limitation with cgroup2

---

boot/kube-proxy.sh
src/patches/kubernetes/0001-kubelet-cm-ignore-sysctl-error-when-running-in-usern.patch
src/patches/kubernetes/0002-kube-proxy-allow-running-in-userns.patch
src/patches/kubernetes/0003-Not-for-Upstream-kubelet-new-cgroup-driver-none.patch

`kube-proxy` turned out to be runnable without patching connTracker,
when the following KubeletConfiguration is specified:
```
conntrack:
maxPerCore: 0
tcpEstablishedTimeout: 0s
tcpCloseWaitTimeout: 0s
```

reduce the amount of the patches

---

boot/rootlesskit.sh
common/cfssl.sh

The original 'hostname' command provided by the project 'net-tools'
doesn't support the option '-I' (see last comment of the 'net-tools'
webpage [1]).
Those tools invoking 'hostname' with the option '-I' (rootlesskit.sh
and cfssl.sh at the time of this writing) work on distros using a
version of 'hostname' supporting '-I' (basically Debian and RedHat
derivatives) out of the box. But it doesn't on those using the original
'hostname' (like ArchLinux and derivatives).
This patch adds support for ArchLinux and derivatives using the default
distro 'hostname' by falling back to using '-i' on those systems not
supporting the option '-I'. The only difference is that it depends on
name resolution (see [2] for the documentation of the option '-I').
[1] https://net-tools.sourceforge.io/
[2] …

improve 'hostname' compatibility

---

Dockerfile

Sometimes it is desirable to mount a volume for usernetes configuration, one use case is that other container can mount same volume and have access to kubeconfig. This change adds volume to `/home/user/.config/usernetes`.

Dockerfile: add volume for usernetes configuration

---

install.sh

#278  solved by using default.target , because systemd in user mode don`t contain multi-user.target
```
systemctl --user -t target
```
how to check
enable autostart service
```
systemctl --user enable u7s.target
```
but command doesn't show any dependensies
```
systemctl --user list-dependencies multi-user.target
```
after changing to default.target
```
systemctl --user list-dependencies default.target
```
and for worker node needs to change parameters in u7s.target delete running master node components
```
Requires=u7s-node.target
After=u7s-node.target
```

There is no multi-user.target in --user mode systemd.

---

README.md

Usernetes (Gen2) should work with "rootful" Docker as well as rootless Docker, but the support for "rootful" is currently broken (issue 297)

README.md: remove mentioning "rootful" Docker

---

Makefile

Avoid printing kubeadm token to the terminal

---

.github/workflows/main.yaml
Dockerfile
Makefile
Makefile.d/check-preflight.sh
Makefile.d/detect_container_engine.sh
README.md
docker-compose.yaml
hack/create-cluster-lxd.sh
hack/create-hosts-lxd.sh
init-host/init-host.root.d/install-podman.sh
init-host/init-host.root.sh
init-host/init-host.rootless.sh

- Dockerfile: Use long image names with the `docker.io/` prefix for compatibility with Red Hat's containers
- Dockerfile: Avoid using BuildKit features that are unsupported by buildah
- docker-compose.yaml: Set the restart mode to `always`, as required by [`podman-restart.service`](https://github.com/containers/podman/blob/v4.6.2/contrib/systemd/system/podman-restart.service.in#L12)
- docker-compose.yaml: Remove `tty: true`, as it is unsupported by `nerdctl compose up -d`.
- Makefile: Remove `$(COMPOSE) cp`, as it is unsupported by podman-compose
nerdctl support depends on:
- containerd/nerdctl#2507 (milestone: nerdctl v1.6.0)

Support CONTAINER_ENGINE=(podman|nerdctl) in addition to docker

---

Makefile.d/check-preflight.sh

Older versions of systemd do not include linger information:
```
$ loginctl list-users --output json 
[{"uid":1000,"user":"anders"}]
```
So usernetes will always show the warning, even if it is enabled.
```
+ loginctl enable-linger anders
[INFO] To run docker.service on system startup, run: `sudo loginctl enable-linger anders`
[WARNING] systemd lingering is not enabled. Run `sudo loginctl enable-linger $(whoami)` to enable it, otherwise Kubernetes will exit on logging out.
```

Remove warning about linger from older systemd

---

Makefile
README.md
docker-compose.yaml

Depends on:
- rootless-containers/bypass4netns#68
- containerd/nerdctl#2916
CI will be added in:
- https://github.com/rootless-containers/usernetes/pull/327

Accelerate networking with bypass4netns

---

init-host/init-host.root.d/install-nerdctl.sh
init-host/init-host.rootless.sh

Depends on:
- containerd/nerdctl#3724

CI: enable bypass4netns

---

.github/workflows/reusable-multi-node.yaml
.github/workflows/reusable-single-node.yaml
Makefile
README.md
hack/create-cluster-lima.sh

The "private" scripts still has the "U7S_" prefix.
This is consistent with other variables such as `HOST_IP` and `NODE_NAME`.
(We can remove the `U7S_` prefix from the "private" scripts too, but they have to be removed at once in another PR)

Makefile: `U7S_PORT_...` -> `PORT_...`
